// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfCvs1phu61ht7IidsYZk23H6VVRiaqJs',
    appId: '1:1029036985859:web:82e08c5445585a1ff98836',
    messagingSenderId: '1029036985859',
    projectId: 'chat-app-81fb8',
    authDomain: 'chat-app-81fb8.firebaseapp.com',
    storageBucket: 'chat-app-81fb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJVC_4bKqAeseCoN9UBxSfQ4ye7i9W3s0',
    appId: '1:1029036985859:android:f8e8937bee2a222af98836',
    messagingSenderId: '1029036985859',
    projectId: 'chat-app-81fb8',
    storageBucket: 'chat-app-81fb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApPAiKuJk4mmQk1pe4q_VfZbes9LGP1gk',
    appId: '1:1029036985859:ios:3ca6687bd58a4342f98836',
    messagingSenderId: '1029036985859',
    projectId: 'chat-app-81fb8',
    storageBucket: 'chat-app-81fb8.appspot.com',
    iosClientId: '1029036985859-7itrl182d7fn2usehmh18k408kdt0dtg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApPAiKuJk4mmQk1pe4q_VfZbes9LGP1gk',
    appId: '1:1029036985859:ios:3ca6687bd58a4342f98836',
    messagingSenderId: '1029036985859',
    projectId: 'chat-app-81fb8',
    storageBucket: 'chat-app-81fb8.appspot.com',
    iosClientId: '1029036985859-7itrl182d7fn2usehmh18k408kdt0dtg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
